### ISSUE TITLE
Enable incremental and snapshot tests

### ISSUE THREAD

**Issue by andyreagan** [mpcarter/dbt-vertica#11]
To pass the tests, I had to turn off these three:

https://github.com/mpcarter/dbt-vertica/blob/a8becee3ccbca7a17083b3c881d1b0e88f344c91/tests/integration.dbtspec#L14-L16

A word of caution: I have found (as have others, as seen in the issues section) that the errors from the [adapter tests](https://github.com/dbt-labs/dbt-adapter-tests) are hard to debug.

**Comment by andyreagan** [comment]
For the snapshot, we need at least this one (see comment https://github.com/mpcarter/dbt-vertica/issues/6#issuecomment-845994471):

https://github.com/dbt-labs/dbt-core/blob/8442fb66a591c4f5353f8baaaaf62f846c5f5171/core/dbt/include/global_project/macros/materializations/snapshots/snapshot_merge.sql#L7-L25

**Comment by ahedengren** [comment]
Incremental tests are now completed. - [PR #13](https://github.com/mpcarter/dbt-vertica/pull/13)

**Comment by ahedengren** [comment]
Snapshot tests and implementation are waiting for review - [PR #14](https://github.com/mpcarter/dbt-vertica/pull/14)
