### ISSUE TITLE
dbt seed: Try to implement COPY FROM LOCAL file 

### ISSUE THREAD

**Issue by chapsuk** [mpcarter/dbt-vertica#2]
Hi @mpcarter ! 

The current seed process can take many time for small datasets, Vertica not optimized for row by row inserts. 
How you think is it possible to implement [COPY FROM LOCAL](https://www.vertica.com/docs/9.2.x/HTML/Content/Authoring/AdministratorsGuide/BulkLoadCOPY/UsingCOPYAndCOPYLocal.htm) load in adapter?

Thanks for the project 👍

**Comment by mpcarter** [comment]
I would think so. I have not tested the seed functionality with Vertica yet, but I will check it out.

**Comment by mpcarter** [comment]
COPY FROM LOCAL should be default now for loading seed data. Update to dbt-vertica 0.18.2.

**Comment by chapsuk** [comment]
Awesome! 

After upgrade i got success `dbt seed` but seed tables was empty, after debug i found error on copy query:

```
copy "docker"."broapp"."events_bro" (from_bro, to_bro, created_at) from local '/<path_to<seeds>/events_bro.csv' delimiter ',' enclosed by '"' skip 1 abort on error rejected data as table broapp.rejected_seeds;
ERROR 5767:  Cannot do LOCAL and REJECTED DATA AS TABLE in the same query; rejected records can only be saved to one location
HINT:  COPY FROM STDIN and REJECTED DATA AS TABLE can be used together
```

remove `REJECTED DATA AS TABLE` fixed that and `dbt seed` feel up all tables. 

Would be nice catch errors from vertica and place rejected logs to local path. Thanks!
