### ISSUE TITLE
seed.sql

### ISSUE THREAD

**Issue by TrololoLi** [mpcarter/dbt-vertica#4]
Hi Matthew,
I am running dbt-vertica 15.0 (I need dbt 0.17.2) but I got an error at the "dbt seed" step : 

"dbt found two macros with the name "basic_load_csv_rows" in the namespace "dbt". Since these macros have the same name and exist in the same namespace, dbt will be unable to decide which to call. To fix this, change the name of one of these macros:
  - macro.dbt_vertica.basic_load_csv_rows (macros/materializations/seed.sql)
  - macro.dbt_vertica.basic_load_csv_rows (macros/materializations/seed.sql)"

Could you please check the reason of that? 
Thanks a lot for your adapter for dbt!
Kind regards,
Tanya  
![image](https://user-images.githubusercontent.com/14012678/110549800-a8d11a00-8143-11eb-99a0-73e115d19183.png)

**Comment by mpcarter** [comment]
Thanks for using the adapter! Sorry to hear about the issue. Hard for me to know for sure what is causing your problem. It almost looks like you have two installations of the adapter?

I do know that in the first version (15.0) that you are using, seed support was not very well tested. In fact, I'm pretty sure it did not work. It works much better and more efficiently in the latest version (18.2).  

I also see your comment about having to use dbt 0.17.x, which is a bummer. A simple update would solve the problem. 

One thing you could try to see if it fixes (or gives a different error which might help narrow down the cause) is to edit the seed.sql file in your install. Assuming you are following best practice of running dbt inside a python virtual environment, then you should be able to go to `venv/Lib/site-packages/dbt/include/vertica/macros/materializations/seed.sql` and manually edit the file. Try changing the name of the macro there to something else and see if the error changes or goes away.

**Comment by TrololoLi** [comment]
Hi mpcarter! I tried it again and works great, I don't use seed anymore (no need for that). Also I found out that "Using a custom profile directory" doesn't work in your package (https://docs.getdbt.com/dbt-cli/configure-your-profile), but I simply use .dbt default folder for my profiles.yml . Thanks a lot for your work!

**Comment by mpcarter** [comment]
@TrololoLi  I've used custom profile directory. Without any other info to go on, I'm not sure what would have caused your trouble. If you are still seeing it then I would open another issue for it. Thanks!
