### ISSUE TITLE
Running dbt snapshot succeeds the first time and fails in the subsequent run to the dbt snapshot

### ISSUE THREAD

**Issue by santoshkrs** [mpcarter/dbt-vertica#6]
Hi Matthew,
I am using DBT and dbt snapshot with timestamp strategy within one model and facing the issue. Running dbt snapshot succeeds the first time and fails in the subsequent run to the dbt snapshot.

This issue may be related to the dbt-vertica adapter. It is reporting the below error.

 Severity: ERROR, Message: Syntax error at or near ")", Sqlstate: 42601, Position: 649, Routine: base_yyerror, File: /data/qb_workspaces/jenkins2/ReleaseBuilds/Grader/REL-9_2_1-x_grader/build/vertica/Parser/scan.l, Line: 1043, Error Code: 4856, SQL: '/* {"app": "dbt", "dbt_version": "0.18.1", "profile_name": "default", "target_name": "dev", "node_id": "snapshot.my_new_project.user_snap"} */       merge into "investigate"."snapshots_dev"."user_snap" as DBT_INTERNAL_DEST     using "user_snap__dbt_tmp" as DBT_INTERNAL_SOURCE     on DBT_INTERNAL_SOURCE.dbt_scd_id = DBT_INTERNAL_DEST.dbt_scd_id     when matched      and DBT_INTERNAL_DEST.dbt_valid_to is null      and DBT_INTERNAL_SOURCE.dbt_change_type = \'update\'         then update         set dbt_valid_to = DBT_INTERNAL_SOURCE.dbt_valid_to     when not matched      and DBT_INTERNAL_SOURCE.dbt_change_type = \'insert\'         then insert ()         values ()     ;   '
  compiled SQL at target\run\my_new_project\snapshots\catalog_information\user_snapshot.sql

Done. PASS=1 WARN=0 ERROR=1 SKIP=0 TOTAL=2

**Further Analysis** 
After analyzing further, I have noticed the following issue in the merge query.
•	Insert and value clause are empty
•	The temp table is not created in Vertica database i.e user_snap__dbt_tmp

**Environment**
Running with dbt=0.18.1
dbt version: 0.18.1
python version: 3.8.5

**Generated DDL source code in Vertica** 
CREATE TABLE snapshots.user_snap
(
...
  dbt_scd_id varchar(32),
    dbt_updated_at timestamptz,
    dbt_valid_from timestamptz,
    dbt_valid_to timestamptz
);

**Model Code Snippet:**
 
{% snapshot user_snap %}

{{
    config(
      target_database='investigate',
      target_schema='snapshots',
      unique_key='id',
      strategy='timestamp',
      updated_at='change_date'
    )
}}
SELECT
....
change_date::timestamptz,
    changed_by::varchar(255),
    hist::boolean,
    original_create_date::timestamptz,
    create_date::timestamptz,
    delete_date::timestamptz,
    ts::timestamptz AS entity_begin_effective_time,
    NULL::timestamptz AS entity_end_effective_time,
    'identity'::VARCHAR(255) as entity_class_type
FROM
        {{ source('public', "user_metric_saas")}} su
    {% if is_incremental() %}
        WHERE ts > {{get_last_execution_time('suser')}}
    {% endif %}
{% endsnapshot %}

Need your help in further analyzing the issue.

**Comment by santoshkrs** [comment]
Hi Matthew,
I have developed another model using the dbt snapshot with **check strategy** and getting the below issue. 

Running with dbt=0.18.1
[WARNING]: Configuration paths exist in your dbt_project.yml file which does not apply to any resources.
There are 1 unused configuration paths:
- models.my_new_project.example

Found 25 models, 4 tests, 2 snapshots, 0 analyses, 315 macros, 0 operations, 0 seed files, 13 sources

14:05:23 | Concurrency: 1 threads (target='dev')
14:05:23 |
14:05:23 | 1 of 2 START snapshot snapshots_dev.application_igasaas_snapshot..... [RUN]
Unhandled error while executing snapshot.my_new_project.application_igasaas_snapshot
**ERROR: snapshot_string_as_time macro not implemented for adapter vertica**
14:05:26 | 1 of 2 ERROR snapshotting snapshots_dev.application_igasaas_snapshot. [ERROR in 2.48s]
14:05:26 | 2 of 2 START snapshot snapshots_dev.user_igasaas_snapshot............ [RUN]
14:05:29 | 2 of 2 OK snapshotted snapshots_dev.user_igasaas_snapshot............ [-1 in 2.96s]
14:05:31 |
14:05:31 | Finished running 2 snapshots in 28.44s.

Completed with 1 error and 0 warnings:

ERROR: snapshot_string_as_time macro not implemented for adapter Vertica

I am having a very short time for my release. After looking into your comment, it looks to me that the snapshot is not supported by this adapter. I have cloned your git code and if your guide further then I can proceed further in implementing the snapshot functionality.
Do You have any other way of communication with u for further discussion on this issue?

**Comment by ahedengren** [comment]
Hi @santoshkrs ,

Snapshots should be ready with the latest version of the adapter once peer review is completed.
