### ISSUE TITLE
Unable to connect to Vertica wth SSL. Is there a way to provide this as input in profile.

### ISSUE THREAD

**Issue by puneetjain007** [mpcarter/dbt-vertica#7]
I am connecting to Vertica instance with SSL and it is failing with below error 

Authentication failed for username "user1", Sqlstate: 28000, Routine: auth_failed, File: /data/qb_workspaces/jenkins2/ReleaseBuilds/Hammermill/REL-10_0_1-x_hammermill/build/vertica/Basics/ClientAuthentication.cpp, Line: 1012, Error Code: 2248

I tried adding ssl: true in profile but did not help.

Same works with vertica_python after setting ssl: True in connection info.

**Comment by andyreagan** [comment]
This is fixed on the current version on github here.

Fixed via: https://github.com/mpcarter/dbt-vertica/commit/b4ce8c8205436fe57cd7de916342b844de007248
